size: nano
num_classes: 10
pretrained: null
data: null
data_dir: /tmp/test_dataset
imgsz: 416
epochs: 2
batch_size: 1
device: auto
optimizer: sgd
lr: 0.01
momentum: 0.9
weight_decay: 0.0005
nesterov: true
scheduler: yoloxwarmcos
warmup_epochs: 5
warmup_lr_start: 0.0
no_aug_epochs: 15
min_lr_ratio: 0.05
mosaic_prob: 1.0
mixup_prob: 1.0
hsv_prob: 1.0
flip_prob: 0.5
degrees: 10.0
translate: 0.1
mosaic_scale: !!python/tuple
- 0.1
- 2.0
mixup_scale: !!python/tuple
- 0.5
- 1.5
shear: 2.0
obj_loss_weight: 1.0
cls_loss_weight: 1.0
iou_loss_weight: 5.0
l1_loss_weight: 1.0
ema: false
ema_decay: 0.9998
amp: false
save_dir: runs/train
save_interval: 1
eval_interval: 10
num_workers: 0
log_interval: 1
seed: 0
